sudo: false
language: cpp
os: linux
dist: trusty

before_install:
# Install conan
- pip install conan
# Automatic detection of your arch, compiler, etc.
- conan user

matrix:
  include:
    - env: COMPILER=clang++-4.0
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - cmake
    - env: COMPILER=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-5
            - gcc-5

install:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
script:
- mkdir build
- cd build
- conan install --build missing --file ../conanfile.txt -s compiler=$CXX
- cmake ../
- make
- make test

