sudo: false
language: cpp
os: linux
dist: trusty

before_install:
# Install conan
- pip install conan
# Automatic detection of your arch, compiler, etc.
- conan user

matrix:
  include:
    - env: COMPILER_NAME=clang-4.0 CXX=clang++-4.0 CC=clang-4.0
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - cmake
    - env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-5
            - gcc-5

script:
- mkdir build
- cd build
- conan install --build missing --file ../conanfile.txt
- cmake ../
- make
- make test

