sudo: false
language: cpp
os: linux
dist: trusty
cache: ccache

before_install:
# Install conan
- pip install conan
# Automatic detection of your arch, compiler, etc.
- conan user

matrix:
  include:
    - env: COMPILER_CXX=clang++-4.0 COMPILER_CC=clang-4.0 COMPILER=clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - cmake
    - env: COMPILER_CXX=g++-5 COMPILER_CC=gcc-5 COMPILER=gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-5
            - gcc-5

install:
  - if [[ "${COMPILER_CXX}" != "" ]]; then export CXX=${COMPILER_CXX}; fi
  - if [[ "${COMPILER_CC}" != "" ]]; then export CC=${COMPILER_CC}; fi
script:
- mkdir build
- cd build
- conan install --build missing --file ../conanfile.txt

- cmake ../
- make
- make test

